BEGIN;
ALTER TABLE non_serialized_items DROP CONSTRAINT non_serialized_items_unique_constraint;
ALTER TABLE non_serialized_items ADD CONSTRAINT non_serialized_items_item_category_id_location_id_key UNIQUE (item_category_id, location_id);
COMMIT;
