DROP INDEX IF EXISTS idx_users_discord_id;
ALTER TABLE users DROP COLUMN IF EXISTS discord_id;
ALTER TABLE users DROP COLUMN IF EXISTS discord_username;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS auth_provider;
ALTER TABLE users ALTER COLUMN password_hash SET NOT NULL;
