// ── Flow node: backend/metadata/parse-pyrcode ──
// Generated by Flow Studio from flow/backend/metadata/parse-pyrcode.yaml. Edit the contract there; only the marked regions below belong to the implementer.
package metadata

// <flow:imports>
import "errors"
import "regexp"
import "strconv"
import "strings"

// </flow:imports>

type ParsePyrcodeInput struct {
	Code string `json:"code"`

	Categories []string `json:"categories"`
}

type ParsePyrcodeOutput struct {
	Category string `json:"category"`

	Number int64 `json:"number"`

	Copy int64 `json:"copy"`
}

// <flow:helpers>
const pyrCodePrefix = "PYR-"

// pyrSuffixPattern matches the number and optional copy number that follow a category's pyr_id.
var pyrSuffixPattern = regexp.MustCompile(`^([0-9]+)(?:-([0-9]+))?$`)

// </flow:helpers>

/* ParsePyrcode: The parts of a Pyrcode — the category's pyr_id, the item's number and, for a numbered copy, the copy number — or an error when the text isn't one. */
func ParsePyrcode(input ParsePyrcodeInput) (ParsePyrcodeOutput, error) {
	// <flow:body>
	if !strings.HasPrefix(input.Code, pyrCodePrefix) {
		return ParsePyrcodeOutput{}, errors.New("not a Pyrcode")
	}
	remainder := input.Code[len(pyrCodePrefix):]

	var bestCategory, bestSuffix string
	for _, category := range input.Categories {
		if category == "" || len(category) <= len(bestCategory) {
			continue
		}
		if !strings.HasPrefix(remainder, category) {
			continue
		}
		suffix := remainder[len(category):]
		if pyrSuffixPattern.MatchString(suffix) {
			bestCategory = category
			bestSuffix = suffix
		}
	}
	if bestCategory == "" {
		return ParsePyrcodeOutput{}, errors.New("not a Pyrcode")
	}

	matches := pyrSuffixPattern.FindStringSubmatch(bestSuffix)

	number, err := strconv.ParseInt(matches[1], 10, 64)
	if err != nil {
		return ParsePyrcodeOutput{}, errors.New("not a Pyrcode")
	}

	var copyNumber int64
	if matches[2] != "" {
		copyNumber, err = strconv.ParseInt(matches[2], 10, 64)
		if err != nil {
			return ParsePyrcodeOutput{}, errors.New("not a Pyrcode")
		}
	}

	return ParsePyrcodeOutput{
		Category: bestCategory,
		Number:   number,
		Copy:     copyNumber,
	}, nil
	// </flow:body>
}
