// Generated by Flow Studio from the examples of backend/metadata/parse-pyrcode. Do not edit — add examples to the node instead.
// checksum: 54a7b194da
package metadata

import "encoding/json"
import "testing"

func TestParsePyrcode1_a_category_and_a_number(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	got, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-LT123", "categories": []any{"LT", "KB"}}))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	sameParsePyrcode(t, got, outputParsePyrcode(map[string]any{"category": "LT", "number": 123, "copy": 0}))
}

func TestParsePyrcode2_a_numbered_copy_of_an_item(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	got, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-KB456-2", "categories": []any{"LT", "KB"}}))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	sameParsePyrcode(t, got, outputParsePyrcode(map[string]any{"category": "KB", "number": 456, "copy": 2}))
}

func TestParsePyrcode3_a_category_whose_pyr_id_ends_in_a_digit(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	got, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-PA41", "categories": []any{"PA", "PA4", "LAP"}}))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	sameParsePyrcode(t, got, outputParsePyrcode(map[string]any{"category": "PA4", "number": 1, "copy": 0}))
}

func TestParsePyrcode4_the_longest_known_category_wins(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	got, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-TV75", "categories": []any{"TV", "TV7", "T75"}}))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	sameParsePyrcode(t, got, outputParsePyrcode(map[string]any{"category": "TV7", "number": 5, "copy": 0}))
}

func TestParsePyrcode5_a_category_nobody_knows_is_not_a_code(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	_, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-ZZ12", "categories": []any{"LT", "KB"}}))
	if err == nil || !containsParsePyrcode(err.Error(), "not a Pyrcode") {
		t.Fatalf("expected an error containing %q, got: %v", "not a Pyrcode", err)
	}
}

func TestParsePyrcode6_a_category_without_a_number_is_not_a_code(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	_, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "PYR-LT", "categories": []any{"LT"}}))
	if err == nil || !containsParsePyrcode(err.Error(), "not a Pyrcode") {
		t.Fatalf("expected an error containing %q, got: %v", "not a Pyrcode", err)
	}
}

func TestParsePyrcode7_without_the_prefix_it_is_not_a_code(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatal(r)
		}
	}()
	_, err := ParsePyrcode(inputParsePyrcode(map[string]any{"code": "LT123", "categories": []any{"LT"}}))
	if err == nil || !containsParsePyrcode(err.Error(), "not a Pyrcode") {
		t.Fatalf("expected an error containing %q, got: %v", "not a Pyrcode", err)
	}
}

func inputParsePyrcode(example map[string]any) ParsePyrcodeInput {
	var in ParsePyrcodeInput
	data := rawParsePyrcode(example)
	in.Code = decodeParsePyrcode[string](data["code"])
	in.Categories = decodeParsePyrcode[[]string](data["categories"])
	return in
}

func outputParsePyrcode(example map[string]any) ParsePyrcodeOutput {
	var out ParsePyrcodeOutput
	data := rawParsePyrcode(example)
	out.Category = decodeParsePyrcode[string](data["category"])
	out.Number = decodeParsePyrcode[int64](data["number"])
	out.Copy = decodeParsePyrcode[int64](data["copy"])
	return out
}

// rawParsePyrcode is the example as encoding/json reads it: numbers float64, objects map[string]any.
func rawParsePyrcode(example map[string]any) map[string]any {
	return decodeParsePyrcode[map[string]any](example)
}

func decodeParsePyrcode[T any](value any) T {
	var out T
	b, err := json.Marshal(value)
	if err == nil {
		err = json.Unmarshal(b, &out)
	}
	if err != nil {
		panic("example value: " + err.Error())
	}
	return out
}

func sameParsePyrcode(t *testing.T, got, want ParsePyrcodeOutput) {
	t.Helper()
	g, _ := json.Marshal(got)
	w, _ := json.Marshal(want)
	if string(g) != string(w) {
		t.Fatalf("got %s, want %s", g, w)
	}
}

func containsParsePyrcode(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
