openapi: 3.0.0
info:
  description: "This is API overview"
  version: 0.1.0
  title: PyrHouse API
  contact:
    email: warrmag7@gmail.com
  license:
    name: MIT
    
security:
  - bearerAuth: [] # use the same name as above    
tags:
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about...
      url: http://swagger.io
paths:
  /auth:
      post:
        tags:
          - auth
        summary: Authorize & generate jwt
        description: ""
        operationId: auth
        requestBody:
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
        responses:
          "201":
            description: created
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string
  /items:
    post:
      tags:
        - item
      summary: Add a new item
      description: ""
      operationId: addItem
      requestBody:
        $ref: "#/components/requestBodies/ItemRequest"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
          description: created
    get:
      tags:
        - item
      summary: NOT IMPLEMENTED YET
      description: ...
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - available
                - pending
                - sold
              default: available
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        "400":
          description: Invalid status value
  /users:
    post:
      tags:
        - users
      summary: Register user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        $ref: "#/components/requestBodies/UserCreateRequest"
        description: Created user object
        required: true
      responses:
        "201":
          description: PROPER RESPONSE NOT IMPLEMENTED YET
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    get:
      tags:
        - users
      summary: Returns collection of users
      description: ...
      responses:
        "200":
          description: List all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
servers:
  - url: pyrhouse-backend-f26ml.ondigitalocean.app
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for 
  requestBodies:
    ItemRequest:
      content:
        application/json:
          schema:
            properties:
              serial:
                type: string
              category_id:
                type: string
    UserCreateRequest:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/UserRequest"
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
      description: List of user object
      required: true
    Item:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Item"
    ItemCategory:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ItemCategory"
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Item:
      type: object
      properties:
        id:
          type: integer
        serial:
          type: string
        category:
          type: string
    ItemCategory:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          description: "example: laptop"       
        label:
          type: string
          description: "example: Laptop"
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        fullname:
          type: string
#         password:
#           type: string
        role:
          type: string
    UserRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        fullname:
          type: string
        role:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
