openapi: 3.1.0
info:
  description: "This is API overview"
  version: 0.1.0
  title: PyrHouse API
  contact:
    email: warrmag7@gmail.com
  license:
    name: MIT
    
security:
  - bearerAuth: [] # use the same name as above    
# tags:
#   - name: users
#     description: Operations about user
#     externalDocs:
#       description: Find out more about...
#       url: http://swagger.io
paths:
  /openapi.html:
    get:
      summary: Get docs
      responses:
        "200":
          description: Serves docs in html format
  /health:
    get:
      summary: Health
      description: Basic health endpoint
      responses:
        "200":
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: ok

          description: Serves docs in html format
  /auth:
    post:
      tags:
        - auth
      summary: Authorize & generate jwt
      description: ""
      operationId: auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin
      responses:
        "201":
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /items:
    get:
      tags:
        - items
      description: Returns array of items both with serial and with quantity
      responses:
        "200":
          description: List of combined stock items and assets
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: "#/components/schemas/Item"
            
  /assets:
    post:
      tags:
        - asset
      summary: Add a new asset
      description: ""
      operationId: addItem
      requestBody:
        $ref: "#/components/requestBodies/ItemRequest"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
          description: created

  /assets/pyrcode/{pyrcode}:
    get:
      tags: 
        - asset
      deprecated: false
      parameters:
        - in: path
          name: pyrcode
          schema:
            type: string
          required: true
          description: Barcode value of item
      responses:
        "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Item"
        "404":
            description: not found
  /assets/{assetID}:
    delete:
      tags: 
        - asset
      deprecated: false
      parameters:
        - in: path
          name: assetID
          schema:
            type: integer
          required: true
          description: Numeric ID of the asset
      responses:
        "200":
            description: successful operation
            content:
              application/json:
                schema:
                  properties:
                    message:
                      type: string
        "409":
            description: unable to delete asset, asset already moved or unavailable 
            content:
              application/json:
                schema:
                  properties:
                    message:
                      type: string
  /stocks:
    post:
      tags:
        - stock
      summary: Register stock item
      description: Create stock item
      requestBody:
        content:
          application/json:
            schema:
              properties:
                category_id:
                  type: integer
                  example: 4
                  required: true
                  description: category of stock
                quantity:
                  type: integer
                  example: 99
                  required: true
      responses:
        "201":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockItem"
        "500":
          $ref: "#/components/responses/DefaultError"
  
  /locations:
    post:
      tags:
        - location
      summary: Create new location (Czteropak)
      description: ""
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  name:
                    type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        "400":
          description: Invalid payload
        "409":
          description: Name already taken
  /locations/{locationID}/assets: 
    get:
      tags:
        - location
      summary: Get list of assets and stock items in given location to-refactor path
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: "#/components/schemas/Item"
                  stock_items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Stock"
        "500":
          description: todo error handling
          $ref: "#/components/responses/DefaultError"
  /locations/{locationID}:
    delete:
      tags:
        - location
      summary: Remove location by ID
      parameters:
        - in: path
          name: locationID
          schema:
            type: integer
          required: true
          description: Numeric ID of the location
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Location deleted successfully
        "409":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"

  /transfers:
    post:
      tags:
        - transfer
      summary: Register transfer
      description: Create transfer of items
      requestBody:
        $ref: "#/components/requestBodies/TransferRequest"
        required: true
  
  /transfers/{transferID}:
    get:
      tags:
        - transfer
      summary: Returns collection of users
      description: ...
      responses:
        "200":
          description: List all users
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: "#/components/schemas/Transfer"

  /transfers/{transferId}/confirm:
    patch:
      tags:
        - transfer
      description: Update transfer status
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - completed
                      - confirmed
                      - in_transit
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  transfer_id:
                    type: integer
                    example: 3
                  status:
                    type: string
                    example: completed
                  message:
                    type: string
                    example: happy message
        "500":
          description: Backend unable to update transfer status
          $ref: "#/components/responses/DefaultError"

  /transfers/{transferId}/assets/{itemId}/restore-to-location:
    patch:
      tags:
        - transfer
      description: Update transfer status
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  location_id:
                    type: integer
                    example: 1
                    description: id of location where to restore item
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                # TODO unify with STOCKs
                  transfer_id:
                    type: integer
                    example: 3
                    description: Location deleted successfully      
        "400":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"
  /transfers/{transferId}/categories/{categoryId}/restore-to-location:
    patch:
      tags:
        - transfer
      description: Update transfer status
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  location_id:
                    type: integer
                    example: 1
                    description: id of location where to restore item
                  quantity:
                    type: integer
                    example: 32
                    description: what amount should be moved from current location
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Stock item removed from transfer successfully      
        "400":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"
  /items/categories:
    post:
      tags:
        - item category
      summary: Register user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: laptop       
                label:
                  type: string
                  example: Laptop
      responses:
        "201":
          description: Category created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCategory"
        "400":
          $ref: "#/components/responses/DefaultError"        
    get:
      tags:
        - item category
      summary: Returns collection of users
      description: ...
      responses:
        "200":
          description: List all users
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: "#/components/schemas/ItemCategory"
  /items/categories/{categoryID}:
    delete:
      tags: 
        - item category
      deprecated: false
      parameters:
        - in: path
          name: categoryID
          schema:
            type: integer
          required: true
          description: Numeric ID of the item category
      responses:
        "200":
            description: successful operation
            content:
              application/json:
                schema:
                  properties:
                    message:
                      type: string
        "409":
            description: unable to delete asset, asset already moved or unavailable 
            content:
              application/json:
                schema:
                  properties:
                    message:
                      type: string
  /users:
    post:
      tags:
        - users
      summary: Register user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        $ref: "#/components/requestBodies/UserCreateRequest"
        description: Created user object
        required: true
      responses:
        "201":
          description: PROPER RESPONSE NOT IMPLEMENTED YET
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    get:
      tags:
        - users
      summary: Returns collection of users
      description: ...
      responses:
        "200":
          description: List all users
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/User"
servers:
  - url: pyrhouse-backend-f26ml.ondigitalocean.app/api
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for 
  responses:
    DefaultError:
      description: Operation failed location has stock/assets already
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  requestBodies:
    ItemRequest:
      content:
        application/json:
          schema:
            properties:
              serial:
                required: true
                type: string
              category_id:
                required: true
                type: string
              origin:
                required: true
                type: string
                description: Where is it from, default types are enum, but it allows to pass also personal & other, it just need to contain "keyword" to pass like druga-era-external
                enum:
                  - druga-era
                  - probis
                  - targowe
                  - personal-{}
                  - other-{}

    TransferRequest:
      content:
        application/json:
          schema:
            properties:
              from_location_id:
                type: string
                example: 1
                required: true
                description: origin location
              location_id:
                type: string
                example: 1
                required: true
                description: desired location, invalid name-to fix
              items:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      required: true
                      type: integer
                      format: int64
                    quantity:
                      type: integer
                      format: int32

    UserCreateRequest:
      content:
        application/json:
          schema:
            type: array
            assets:
              $ref: "#/components/schemas/UserRequest"
    UserArray:
      content:
        application/json:
          schema:
            type: array
            assets:
              $ref: "#/components/schemas/User"
      description: List of user object
      required: true
    Item:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Item"
    ItemCategory:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ItemCategory"
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Error:
      type: object
      properties:
        error:
          type: string
          example: Could not delete location
        details:
          type: string
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 321
        serial:
          type: string
          example: XYZ321
        pyrcode:
          type: string
          example: PYR0L100
        location:
          $ref: "#/components/schemas/Location"
        category:
          $ref: "#/components/schemas/ItemCategory"

    Stock:
      type: object
      properties:
        id:
          type: integer
        category:
          $ref: "#/components/schemas/ItemCategory"
        quantity:
          type: integer
    ItemCategory:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          example: asset 
        name:
          type: string
          example: laptop       
        label:
          type: string
          example: Laptop
    Location:
      type: object
      properties:
        id: 
          type: integer
          example: 3
        name:
          type: string
          example: "Gzdaczroom"
    Transfer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        from_location:
          $ref: "#/components/schemas/Location"
        to_location:
          $ref: "#/components/schemas/Location"
        assets:
          type: array
          items:
            $ref: "#/components/schemas/Item"
        stock_items:
          type: array
          items:
            $ref: "#/components/schemas/Stock"
        transfer_date:
          type: date-time
        status:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        fullname:
          type: string
#         password:
#           type: string
        role:
          type: string
    StockItem:
      type: object
      properties:
        id:
          type: integer
        category_id:
          type: integer
          example: 4
        quantity:
          type: integer
          example: 99
    UserRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        fullname:
          type: string
        role:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
